---
title: "Model Table"
author: "Livio Silva-Muller"
date: "2023-02-01"
output: html_document
---

````{=tex}
\begin{landscape}

```{r table 1, fig.cap="Models Description", echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, include=TRUE}

models <- tibble::tribble(~"", ~Description,
                          "Model", "",
                          "Fixed-effects logistic regressions indexed by the president", "The regression method allows to control for variables not measured (e.g. ideology) related to individuals (i.e. presidents) [see @allison2009].",
                          "Dependent variables", "",
                          "Problem constructions", "Pure environmental conservation; pure economic integration; pure social development; and pure national sovereignty.",
                          "Independent variable", "",
                          "Settings", "Setting where speech occurs as (1) non-Amazonian Brazilian states, (2) Brasilia, (3) Amazonian countries, and (4) international, in relation to the reference category of Amazonian states within Brazil.",
                          "Control variables", "",
                          "Deforestation rates", "Lagged yearly deforestation rates as a control for the possible relationship between deforestation rates and Amazonian problem-constructions.",
                          "Election year", "Election years are controls for possible discursive changes related to the Amazon for these years.",
                          "Inflation rate",  "Average yearly inflation rates as a control for a possible relationship between economic conditions/fluctuations and problem constructions.",
                          "High-profile environmental event", "Years in which high-profile environmental events occurred control for the frequency and, possibly, how the Amazon was constructed as a problem in discourse for those years.")
                         
kbl(models, booktabs = T, caption = "Model description") %>%
kable_styling(latex_options = c("striped", "repeat_header", "scale_down"),position= "center", font_size = 9, full_width = TRUE) %>% row_spec(c(1,3,5,7), bold = TRUE, italic = TRUE)

```

\end{landscape}
````